//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mamaev_pr23._06.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int IDPartnerProduc { get; set; }
        public int IDProduct { get; set; }
        public int IDPartner { get; set; }
        public int KolvoProduct { get; set; }
        public System.DateTime DateOfSell { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Product Product { get; set; }
    }
}
